version: '3.7'

services:
  mysql:         
    build: ./mysql
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: 'campaign'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10            
  spark:
    build: ./pyspark
    container_name: spark
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    command: sh -c "sleep 10s ; spark-submit --master local compute_segments.py"
  flask:
    build: ./api
    container_name: api
    restart: always
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"
    depends_on:
            - mysql
    command: sh -c "sleep 10s ; python3 app.py -h='0.0.0.0'"
